baseurl                 = "https://huanglipang.ml/"     # Your domain name. Must end with "/"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "Li-Pang Huang"
theme                   = "sam"
pygmentsStyle           = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
googleAnalytics         = "UA-128377666-1"              # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Oct 29, 2018"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "sam.ico"
    homepage            = "home"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = false                         # Allow links to the full size images
    smallPreviewImages  = true                          # Show small images from the subfolder instead of the big versions in the gallery
                                                        # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                     # The subfolder for the small versions of the images under the gallery (with trailing slash)
                                                        # For each image the small version has to have the same filename as the big version.
    footerText          = "Powered by [Hugo](https://gohugo.io/) with [Sam](https://themes.gohugo.io/hugo-theme-sam/)."

# Metadata
    description         = "Li-Pang Huang"                 # Max 160 characters show in search results
    twitterCard         = "summary_large_image"           # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "huanglipang_tn.png"            # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/about"
    text = "who"

[[params.mainMenu]]
    link = "/presentations"
    text = "talks"

[[params.mainMenu]]
    link = "/projects"
    text = "what"